PARSER_BEGIN(Example)

public class Example {
    public static void main(String[] args) throws ParseException{
      Example parser = new Example(System.in);
      parser.Aritm();
    }
}

PARSER_END(Example)

SKIP : {
" " | "\t" | "\r"
}

TOKEN : {
< INTEGER : (["0" - "9"])+ >
| < LF : "\n">
}

void Aritm() : {Token t1,t2;}
{
    t1=<INTEGER> {
        System.out.println("Integer = "+t1.image);
    }
    ( ("+" | "-") t2=<INTEGER> {
        System.out.println("Integer = "+t2.image);
    }
    )? <LF>
}