/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.9 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTTERM = 6;
  public int JJTASSIGNEMNT = 7;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
    "Assignemnt",
  };
}
/* JavaCC - OriginalChecksum=5275d7a206e0e38ee648141d628dc02f (do not edit this line) */
