/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.9 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=a5c702956be14b1816565c2327442f5e (do not edit this line) */
